name: WardenAnticheat
version: '${project.version}'
main: hu.ClashRoyale456.wardenAnticheat.WardenAnticheat
api-version: '1.21'
author: ClashRoyale456
depend:
  - packetevents
  - PlaceholderAPI
softdepend:
  - floodgate

commands:
  warden:
    description: Warden Anticheat main command
    usage: /warden <subcommand>
    permission: warden.use

permissions:
  warden.use:
    description: Warden commands use perm
    default: op
  warden.help:
    description: Help use permission
    default: op
  warden.playerinfo:
    description: See player informations
    default: op
  warden.violations:
    description: See violations
    default: op
  warden.alerts:
    description: Alerts on/off
    default: op
  warden.kick:
    description: Kick player
    default: op
  warden.ban:
    description: Ban player
    default: op
  warden.reload:
    description: Reload config
    default: op
  warden.bypass:
    description: Anticheat bypass
    default: false